### ISSUE TITLE
cached __providedBy__ in plone.dexterity 2.4.3

### ISSUE THREAD

**Issue by huubbouma** [collective/collective.instancebehavior#2]
I have an issue when I have enabled a new behavior (with a NamedBlobImage) on a document in plone 5.0.6 and then try to save it. 

I think it's because of the ``__providedBy__`` functionality in plone.dexterity 2.4.3.
I don't see this issue happening in a previous plone 4 site, and I think the important difference is in the way the caching is invalidated by looking at subtypes in the FTIAwareSpecification decorator. but this is just a guess.

In my behavior I have a NamedBlobImage field which triggers the error upon saving it.
The versionbehavior modifier does this call:
`prior_blob = field.get(field.interface(prior_obj))`
(see stacktrace below)

I now work around this issue by fixing it in the versionbehavior modifier and ignore the exception but perhaps someone know how to fix this properly?

```
  Module plone.app.versioningbehavior.subscribers, line 62, in create_version_on_save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 303, in save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 448, in _recursiveSave
  Module Products.CMFEditions.ArchivistTool, line 265, in prepare
  Module Products.CMFEditions.ModifierRegistryTool, line 141, in getReferencedAttributes
  Module plone.app.versioningbehavior.modifiers, line 136, in getReferencedAttributes
TypeError: ('Could not adapt', <Document at /Plone/en/hoi>, <SchemaClass myproject.theme.behaviors.frontpage.IShowOnFrontPage>)

```

**Comment by thet** [comment]
Sounds like this could have been solved via: https://github.com/collective/collective.instancebehavior/commit/30d904d44518f46828d3ad740a4ec6b8a4cf5540

**Comment by huubbouma** [comment]
Yes, I don't see this issue happening now, so it's been fixed. Thanks for fixing @jensens and for letting me know @thet
